name: OIDC demo

on:
 push:
  branches: ["master"]

permissions:
 id-token: write
 contents: read


jobs:
 OIDC_build:
  runs-on: ubuntu-latest
  steps: 
   - name: checkout source
     uses: actions/checkout@v4
   - name: configuring aws credentials using OIDC
     uses: aws-actions/configure-aws-credentials@v4.1.0
     with:
       aws-region: ap-south-1
       role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
   - name: test aws credentals
     run: aws sts get-caller-identity 
     
       
